name: ovo
description: OvO is a Dart-first schema declaration and validation library.
version: 0.0.0
repository: https://github.com/medz/ovo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
