name: ovo
description: OvO is a Dart-first schema declaration and validation library.
version: 0.0.1
repository: https://github.com/medz/ovo

environment:
  sdk: ^3.1.5

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
